[build]
  # Отключаем установку зависимостей - это статический сайт
  ignore = "git diff --quiet $CACHED_COMMIT_REF $COMMIT_REF"
  
[build.environment]
  # Указываем что это статический сайт
  NODE_VERSION = "18"

# Настройки для статических файлов
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# Кэширование для статических ресурсов
[[headers]]
  for = "/*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Основной HTML без кэширования для обновлений
[[headers]]
  for = "/*.html"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"